<a href="https://colab.research.google.com/github/Mochismo/LearnPython/blob/main/Additional_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Problem 2
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8,-9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
c_ndarray = np.matmul(a_ndarray, b_ndarray)
print(c_ndarray)
print(a_ndarray @ b_ndarray)


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [23]:
#Problem 3(1)
A=[[-1,2,3],[4,-5,6],[7,8,-9]]
B=[[0,2,1],[0,2,-8],[2,9,-1]]
# result is 3x3
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

# iterate through rows of A
for i in range(len(A)):
   # iterate through columns of B
   for j in range(len(B[0])):
       # iterate through rows of B
       for k in range(len(B)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


In [22]:
# Problem 3

# 3x3 matrix
X = [[-1,2,3],
    [4 ,-5,6],
    [7 ,8,-9]]

# 3x4 matrix
Y = [[0,2,1],
    [0,2,-8],
    [2,9,-1]]

# result is 3x4
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)


[6, 29, -20]
[12, 52, 38]
[-18, -51, -48]


In [32]:
#Problem 4
A=[[-1,2,3],[4,-5,6],[7,8,-9]]
B=[[0,2,1],[0,2,-8],[2,9,-1]]
C = []
for i in range(0,len(A)):
  temp=[]
  for j in range(0,len(B[0])):
    s=0
    for k in range(0,len(A[0])):
      s += A[i][k]*B[k][j]
    temp.append(s)
    C.append(temp)
    print(temp)         

[6]
[6, 29]
[6, 29, -20]
[12]
[12, 52]
[12, 52, 38]
[-18]
[-18, -51]
[-18, -51, -48]


In [5]:
Additional 
A=[[-1,2,3],[4,-5,6],[7,8,-9]]
B=[[0,2,1],[0,2,-8],[2,9,-1]]
matrix=[]

def multiplicationLineColumn(line,column):
    try:
        sizeLine=len(line)
        sizeColumn=len(column)
        if(sizeLine!=sizeColumn):
            raise ValueError("Exception")
        res = sum([line[i] * column[i] for i in range(sizeLine)])
        return res
    except ValueError:
        print("sould have the same len line & column")

def  getColumn(matrix,numColumn):
    size=len(matrix)
    column= [matrix[i][numColumn] for i in range(size)]
    return column

def getLine(matrix,numLine):
    line = matrix[numLine]
    return line

for i in range(len(A)):
    matrix.append([])
    for j in range(len(B)):
        matrix[i].append(multiplicationLineColumn(getLine(A,i),getColumn(B,j)))

print(matrix)



[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]
