<a href="https://colab.research.google.com/github/Mochismo/LearnPython/blob/main/Nineteenth_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1

In [57]:
import numpy as np
def scratch_train_test_split(X, y, train_size=0.8, seed=0):
    """Divide the validation data.
    Parameters
    ----------
    X : ndarray
      Training data (n_samples, n_features)
    y : ndarray
      Correct answer value (n_samples,)
    train_size : float
      Specify what percentage to use as a train (0 < train_size < 1)
    Returns
    -------
    X_train : ndarray
      Training data (n_samples, n_features)
    X_test : ndarray
      Validation data (n_samples, n_features)
    y_train : ndarray
      Correct answer value of training data (n_samples,)
    y_test : ndarray
      Correct value of verification data (n_samples,)
    """
    # Write code here
    np.random.seed(seed)
    np.random.shuffle(X)

    np.random.seed(seed)
    np.random.shuffle(y)

    X_elements = len(X)
    y_elements = len(y)

    X_split = int(X_elements*train_size)
    y_split = int(y_elements*train_size)

    X_train, X_test = X[:X_split], X[X_split:]
    y_train, y_test = y[:y_split], y[y_split:]

    return X_train, X_test, y_train, y_test


In [58]:
X_train, X_test, y_train, y_test = scratch_train_test_split(X, y, train_size=0.8)

print(X_train)
print(y_train)

[[-2.29374113e-01  1.90103034e+00]
 [ 2.70709974e+00  5.30195126e-01]
 [ 1.46837064e+00 -1.14147604e+00]
 [ 2.46463255e+00 -2.36692124e-01]
 [ 6.78049440e-01 -2.19208684e+00]
 [-1.26658152e+00  1.97258945e+00]
 [ 1.67483664e+00 -1.55932524e+00]
 [ 2.25701854e+00 -9.84595570e-01]
 [-9.07603154e-01  2.02453103e+00]
 [ 6.91658195e-01  2.83991926e+00]
 [-3.69047331e-03  2.72794750e+00]
 [ 1.64773650e+00 -1.37392022e+00]
 [ 4.22222154e-01 -2.24807641e+00]
 [ 1.76601743e+00 -5.17359929e-01]
 [ 3.64650383e-02  2.26861507e+00]
 [ 2.65071067e+00 -9.47349274e-01]
 [ 2.42340322e+00  4.86925716e-01]
 [ 2.45372019e+00 -1.16225960e-01]
 [-1.60770945e+00  1.29136745e+00]
 [-1.16513883e+00  1.40174924e+00]
 [ 1.19226877e-01  3.62537974e+00]
 [ 2.81410717e+00 -8.51160223e-01]
 [-2.05735708e+00  1.59371720e+00]
 [-1.10375132e+00  2.13604529e+00]
 [-1.00408384e+00  2.76905831e+00]
 [ 2.48267455e+00 -1.06055410e+00]
 [ 1.82068657e-03  4.23559938e+00]
 [ 3.40980745e-01 -4.07908535e+00]
 [-5.93349449e-01  1

In [59]:
print(X_test)
print(y_test)

[[-1.66380709  1.33857783]
 [ 2.75242509 -0.43123816]
 [-0.41766359  2.54908993]
 [ 1.21732779 -0.30296356]
 [ 2.1584315  -0.78199606]
 [ 2.05134476 -1.51073129]
 [ 2.0789714   0.06069619]
 [-1.79135526  1.24591256]
 [-2.22729008  0.97316203]
 [-0.77976867  2.03189184]
 [ 2.49429941 -0.55301141]
 [ 3.02667361  0.57416059]
 [ 2.82851195  0.63557286]
 [ 0.66831964 -1.49110721]
 [ 0.31304912 -2.82240177]
 [ 0.31369184  1.90748822]
 [-0.10446081  3.42956123]
 [ 3.39914935  0.02889014]
 [-1.61844165  1.80967258]
 [ 2.90876329 -0.38490965]
 [ 2.83308619  0.32953692]
 [-0.99950867  2.50800932]
 [ 1.33370272 -2.29635748]
 [ 2.57058557 -0.31821676]
 [ 1.03842491 -0.88881567]
 [ 1.17277691 -1.93810291]
 [-3.0114128   1.1876528 ]
 [-1.96378474  1.23684168]
 [ 2.15599603 -1.04483586]
 [ 2.56168968 -0.96975663]
 [ 1.78641748 -2.83215302]
 [ 1.99620094 -1.51071019]
 [ 0.00915905  2.64306238]
 [ 3.56988241  0.52742304]
 [-0.37124062  2.15602745]
 [ 1.88965323 -1.34422956]
 [ 1.67209737 -1.99907854]
 

In [60]:
import numpy as np
X = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
y = np.array([0,1,2,3,4])
X.shape, y.shape

((5, 3), (5,))

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)
print(X_train)
print(y_train)

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [0 0 0]]
[1 2 3 0]


In [62]:
print(X_test)
print(y_test)

[[4 4 4]]
[4]


Classification Problem 2

In [63]:
from sklearn.datasets import load_iris
import pandas as pd


In [64]:
iris_dataset = load_iris()
columns_list = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
df = pd.DataFrame(iris_dataset['data'], columns= columns_list)
df['target'] = iris_dataset['target']
df = df[df['target'] != 0]
df

sepal_length  sepal_width  petal_length  petal_width  target
50            7.0          3.2           4.7          1.4       1
51            6.4          3.2           4.5          1.5       1
52            6.9          3.1           4.9          1.5       1
53            5.5          2.3           4.0          1.3       1
54            6.5          2.8           4.6          1.5       1
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3       2
146           6.3          2.5           5.0          1.9       2
147           6.5          3.0           5.2          2.0       2
148           6.2          3.4           5.4          2.3       2
149           5.9          3.0           5.1          1.8       2

[100 rows x 5 columns]

In [65]:
X1 = df.drop(['target'], axis=1)
y1 = df.target
X1.shape, y1.shape

((100, 4), (100,))

In [66]:
X1 = X1.to_numpy()
y1 = y1.to_numpy()

Simple DataSet 1

In [67]:
np.random.seed(seed=0)
n_samples = 500
f0 = [-1, 2]
f1 = [2, -1]
cov = [[1.0, 0.8], [0.8, 1.0]]
f0 = np.random.multivariate_normal(f0, cov, int(n_samples/2))
f1 = np.random.multivariate_normal(f1, cov, int(n_samples/2))
X = np.concatenate((f0, f1))
y = np.concatenate((np.ones((int(n_samples/2))), np.ones((int(n_samples/2)))*(-1))).astype(np.int)
random_index = np.random.permutation(np.arange(n_samples))
X2 = X[random_index]
y2 = y[random_index]
X2.shape, y2.shape


((500, 2), (500,))

Simple Dataset 2

In [68]:
X3 = np.array([[-0.44699, -2.8073], [-1.4621, -2.4586],
               [0.10645, 1.9242], [-3.5944, -4.0112],
               [-0.9888, 4.5718], [-3.1625, -3.9606],
               [0.56421, 0.72888], [-0.60216, 8.4636],
               [-0.61251, -0.75345], [-0.73535, -2.2718],
               [-0.80647, -2.2135], [0.86291, 2.3946],
               [-3.1108, 0.15394], [-2.9362, 2.5462],
               [-0.57242, -2.9915], [1.4771, 3.4896],
               [0.58619, 0.37158], [0.6017, 4.3439],
               [-2.1086, 8.3428], [-4.1013, -4.353],
               [-1.9948, -1.3927], [0.35084, -0.031994],
               [0.96765, 7.8929], [-1.281, 15.6824],
               [0.96765, 10.083], [1.3763, 1.3347],
               [-2.234, -2.5323], [-2.9452, -1.8219],
               [0.14654, -0.28733], [0.5461, 5.8245],
               [-0.65259, 9.3444], [0.59912, 5.3524],
               [0.50214, -0.31818], [-3.0603, -3.6461],
               [-6.6797, 0.67661], [-2.353, -0.72261],
               [1.1319, 2.4023], [-0.12443, 9.0162],
               [-2.5677, 13.1779], [0.057313, 5.4681]])
y3 = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
               1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
X3.shape, y3.shape

((40, 2), (40,))

Division of Training Data and Verification Data

In [69]:
X1_train, X1_test, y1_train, y1_test = scratch_train_test_split(X1, y1, train_size=0.8)

X2_train, X2_test, y2_train, y2_test = scratch_train_test_split(X2, y2, train_size=0.8)

X3_train, X3_test, y3_train, y3_test = scratch_train_test_split(X3, y3, train_size=0.8)

Preprocessing/ Standardization

In [70]:
from sklearn.preprocessing import  StandardScaler
scaler = StandardScaler()

scaler.fit(X1_train)
X1_train = scaler.transform(X1_train)
X1_test = scaler.transform(X1_test)

scaler.fit(X2_train)
X2_train = scaler.transform(X2_train)
X2_test = scaler.transform(X2_test)

scaler.fit(X3_train)
X3_train = scaler.transform(X3_train)
X3_test = scaler.transform(X3_test)

Learning and Estimation

SDG

IRIS Data Set

In [71]:
from sklearn.linear_model import SGDClassifier
sdg1 = SGDClassifier(loss='log')
sdg1.fit(X1_train, y1_train)
y_preds1 =sdg1.predict(X1_test)

In [72]:
y_preds1

array([1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1])

In [73]:
sdg1.score(X1_test, y1_test)

0.95

DataSet 1

In [74]:
sgd2 = SGDClassifier(loss='log')
sgd2.fit(X2_train, y2_train)
y_preds2 = sgd2.predict(X2_test)

In [75]:
y_preds2

array([-1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1,  1, -1, -1,
        1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,
       -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,  1, -1,
       -1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1])

In [76]:
sgd2.score(X2_test, y2_test)

1.0

DataSet2

In [77]:
sgd3 = SGDClassifier(loss='log')
sgd3.fit(X3_train, y3_train)
y_preds3 = sgd3.predict(X3_test)

In [78]:
y_preds3

array([0, 1, 0, 0, 0, 1, 0, 0])

In [79]:
sgd3.score(X3_test, y3_test)

0.875

SVM

Iris Dataset

In [80]:
from sklearn.svm import SVC
svc1 = SVC()
svc1.fit(X1_train, y1_train)
y_preds4 = svc1.predict(X1_test)

In [81]:
svc1.score(X1_test, y1_test)

0.95

DataSet 1

In [82]:
svc2 = SVC()
svc2.fit(X2_train, y2_train)
y_preds5 = svc2.predict(X2_test)

In [83]:
svc2.score(X2_test, y2_test)

1.0

DataSet 2

In [84]:
svc3 = SVC()
svc3.fit(X3_train, y3_train)
y_preds6 = svc3.predict(X3_test)

In [85]:
svc3.score(X3_test, y3_test)

0.5

Decission Tree

Iris Dataset

In [86]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier()
dt1.fit(X1_train, y1_train)
y_preds7 = dt1.predict(X1_test)

In [87]:
dt1.score(X1_test, y1_test)

0.95

DataSet 1

In [88]:
dt2 = DecisionTreeClassifier()
dt2.fit(X2_train, y2_train)
y_preds8 = dt2.predict(X2_test)

In [89]:
dt2.score(X2_test, y2_test)

1.0

DataSet 2

In [90]:
dt3 = DecisionTreeClassifier()
dt3.fit(X3_train, y3_train)
y_preds9 = dt3.predict(X3_test)

In [91]:
dt3.score(X3_test, y3_test)

1.0

Problem 3: Creating a code to solve regression problem

DataSet 3

In [92]:
import pandas as pd
trains = pd.read_csv('/content/drive/MyDrive/train.csv')
X4 = trains.loc[:,['GrLivArea', 'YearBuilt']]
y4 = trains.loc[:, 'SalePrice']

X4 = X4.to_numpy()
y4 = y4.to_numpy()

X4.shape, y4.shape


((1460, 2), (1460,))

In [93]:
X4_train, X4_test, y4_train, y4_test = scratch_train_test_split(X4, y4, train_size=0.8)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

scaler.fit(X4_train)
X4_train = scaler.transform(X4_train)
X4_test = scaler.transform(X4_test)

SGD

In [94]:
from sklearn.linear_model import SGDRegressor
reg1 = SGDRegressor()
reg1.fit(X4_train, y4_train)
y_preds10 = reg1.predict(X4_test)

In [95]:
reg1.score(X4_test, y4_test)

0.6499209662086336

In [96]:
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(y4_test, y_preds10)
print('MSE SGD: {:,.3f}'.format(mse1))

MSE SGD: 1,724,280,326.017


SVM

In [98]:
from sklearn.svm import SVR
reg2 = SVR()
reg2.fit(X4_train, y4_train)
y_preds11 = reg2.predict(X4_test)

In [99]:
reg2.score(X4_test, y4_test)

-0.003402281129969209

In [100]:
mse2 = mean_squared_error(y4_test, y_preds11)
print('MSE SGD: {:,.3f}'.format(mse2))

MSE SGD: 4,942,160,613.549


DecisionTree

In [101]:
from sklearn.tree import DecisionTreeClassifier
reg3 = DecisionTreeClassifier()
reg3.fit(X4_train, y4_train)
y_preds12 = reg3.predict(X4_test)

In [102]:
reg3.score(X4_test, y4_test)

0.00684931506849315

In [103]:
mse3 = mean_squared_error(y4_test, y_preds12)
print('MSE SGD: {:,.3f}'.format(mse3))

MSE SGD: 2,591,657,146.000
