<a href="https://colab.research.google.com/github/Mochismo/LearnPython/blob/main/Sixteenth_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1
Classes

1.   pandas.read_csv()
2.   matplotlib.show()
3.   sklearn.ensemble





Problem 2
Explaining methods and instances
1.   pandas.loc()
2.   pandas.iloc()
3.   numpy.sum
4.   numpy.reshape
5.   numpy.ravel

Instance Variable
1.   ndarray.shape
2.   ndarray.ndim
3.   ndarray.dtype
4.   ndarray.size
5.   ndarray.data





In [21]:
# Problem 3
import numpy as np
class ScratchStandardScaler():
  def fit(self, X):
    self.mean_ = np.mean(X, axis=0)
    self.var_ = np.var(X, axis=0)
    pass
  def transform(self, X):
    X_scaled = (X-self.mean_)/self.var_
    pass
    return X_scaled  


In [22]:
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print('mean :{}'.format(scratch_scaler.mean_))
print('distributed :{}'.format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

mean :[4.86 3.31 1.45 0.22]
distributed :[0.0764 0.0849 0.0105 0.0056]
[[  3.14136126   2.23792697  -4.76190476  -3.57142857]
 [  0.52356021  -3.65135453  -4.76190476  -3.57142857]
 [ -2.09424084  -1.29564193 -14.28571429  -3.57142857]
 [ -3.40314136  -2.47349823   4.76190476  -3.57142857]
 [  1.83246073   3.41578327  -4.76190476  -3.57142857]
 [  7.06806283   6.94935218  23.80952381  32.14285714]
 [ -3.40314136   1.06007067  -4.76190476  14.28571429]
 [  1.83246073   1.06007067   4.76190476  -3.57142857]
 [ -6.02094241  -4.82921084  -4.76190476  -3.57142857]
 [  0.52356021  -2.47349823   4.76190476 -21.42857143]]


In [23]:
# Problem 4
def type_judge(value_to_judge):
  if not isinstance(value_to_judge, (int, float)):
    print("Please input only numbers")
    return False
  else:
    return True

class ArthClass():
  #
  #
  #
  def __init__(self, value):
    if(type_judge(value)):
      self.value = value
      print("something{}".format(self.value))
    else:
      self.self_value = value  

  def add(self, value2):

    if type_judge(self.value) and type_judge(value2):
      self.value += value2
    else:
      self.value = "cannot be calculated because one of the values is not a number"

  def sub(self, value2):

    # subtract the received argument with the self.value
    if type_judge(self.value) and type_judge(value2):
      self.value -= value2
    else:
       self.value = "cannot be calculated because one of the values is not a number"

  def mult(self, value2):
     # multiply the received argument with the self.value
    if type_judge(self.value) and type_judge(value2):
       self.value *= value2
    else:
       self.value = "cannot be calculated because one of the values is not a number"

  def div(self, value2):
     # divide the received argument with the self.value
    if type_judge(self.value) and type_judge(value2):
       self.value /= value2
    else:
       self.value = "cannot be calculated because one of the values is not a number"

example = ArthClass(5)
print("value : {}".format(example.value)) 
example.add(3)
print("addition value : {}".format(example.value))

example2 = ArthClass("k") 
example.sub(3)
print("subtaction value : {}".format(example.value))
 
example.mult(3) 
print("multiplication value : {}".format(example.value)) 

example.div('k') 
print("division value : {}".format(example.value))



something5
value : 5
addition value : 8
Please input only numbers
subtaction value : 5
multiplication value : 15
Please input only numbers
division value : cannot be calculated because one of the values is not a number
